= FAU_GEN_EXT Example
:showtitle:
:toc: 
:toclevels: 4
:imagesdir: images
:revnumber: 0.1
:revdate: 2019-08-27

== Introduction
This is an example of FAU_GEN_EXT taken from the collaborative Protection Profile for 
Network Devices created by the Network Devices iTC.

It is important to note that this is for an entire family of requirements. A set of requirements like this can be split between mandatory and selection-based or optional requirements, and so may not be in a single block in the cPP (by convention).

== Extended Component Definitions
This section is what would be placed in the Extended Component Definitions of the cPP (or PP-Module).

=== Security Audit (FAU)

==== Security Audit Data Generation (FAU_GEN_EXT)

===== Family Behaviour
This component defines the requirements for components in a distributed TOE to generate security audit data.

===== Component levelling
[#img-FAU_GEN_EXT,FAU_GEN_EXT.png] 
.Component levelling 
[ditaa]
....
    +---------------------------------------------+
    |                                             |    +---+
    | FAU_GEN_EXT  Security Audit Data Generation +--->| 1 |
    |                                             |    +---+
    +---------------------------------------------+ 
....

FAU_GEN_EXT.1 Security audit data shall be generated by all components in a distributed TOE

===== Management: FAU_GEN_EXT.1

The following actions could be considered for the management functions in FMT:

[loweralpha]
. The TSF shall have the ability to configure the cryptographic functionality.

===== Audit: FAU_GEN_EXT.1
The following actions should be auditable if FAU_GEN Security audit data generation is included in the PP/ST:

[loweralpha]
. No audit necessary

===== FAU_GEN_EXT.1 Security Audit Data Generation for Distributed TOE Components
Hierarchical to: No other components

Dependencies: No dependencies

*FAU_GEN_EXT.1.1* The TSF shall be able to generate audit records for each TOE component. The audit records generated by the TSF of each TOE component shall include the subset of security relevant audit events which can occur on the TOE component.

Application Note 1:: The TOE must be able to generate audit records for each TOE component. Some TOE components of a distributed TOE might not implement the complete TSF of the overall TOE but only a subset of the TSF. The audit records for each TOE component need to cover all security relevant audit events according to the subset of the TSF implemented by this particular TOE component but not necessarily all security relevant audit events according to the TSF of the overall TOE. If a security-relevant event can occur on multiple TOE components, it needs to cause generation of an audit record uniquely identifying the component associated with the event. The ST author shall identify for each TOE component which of the overall required audit events defined in FAU_GEN.1.1 are logged. The ST author may decide to do this by providing a corresponding table. The information provided needs to be in agreement with Table 1. The overall TOE needs to cover all auditable events listed in Table 2 (and Tables 4 and 5 as applicable to the overall TOE).

== Evaluation Activities
This section is what would be placed in the Evaluation Activities of the Supporting Document.

=== EA for FAU_GEN_EXT.1 Security Audit Data Generation for Distributed TOE Components

For distributed TOEs, the requirements on TSS, Guidance Documentation and Tests regarding FAU_GEN_EXT.1 are already covered by the corresponding requirements for FAU_GEN.1.

==== TSS
The evaluator examines the TSS to confirm that it describes which TOE components store their security audit events locally and which send their security audit events to other TOE components for local storage. For the latter, the target TOE component(s) which store security audit events for other TOE components shall be identified. For every sending TOE component the corresponding receiving TOE component(s) need to be identified. For every transfer of audit information between TOE components it shall be described how the data is secured during transfer according to FTP_ITC.1 or FPT_ITT.1.

For each TOE component which does not store audit events locally by itself, the evaluator confirms that the TSS describes how the audit information is buffered before sending to another TOE component for local storage.

==== Guidance Documentation

The evaluator shall examine the guidance documentation to ensure that it describes how the link between different TOE components is established if audit data is exchanged between TOE components for local storage. The guidance documentation shall describe all possible configuration options for local storage of audit data and provide all instructions how to perform the related configuration of the TOE components.

The evaluator shall also ensure that the guidance documentation describes for every TOE component which does not store audit information locally how audit information is buffered before transmission to other TOE components.


==== Tests
For at least one of each type of distributed TOE components (sensors, central nodes, etc.), the following tests shall be performed using distributed TOEs.

Test 1: For each type of TOE component, the evaluator shall perform a representative subset of auditable actions and ensure that these actions cause the generation of appropriately formed audit records. Generation of such records can be observed directly on the distributed TOE component (if there is appropriate interface), or indirectly after transmission to a central location.

Test 2: For each type of TOE component that, in the evaluated configuration, is capable of transmitting audit information to the external audit server (as specified in FTP_ITC.1), the evaluator shall configure a trusted channel and confirm that audit records generated as a result of actions taken by the evaluator are securely transmitted. It is sufficient to observe negotiation and establishment of the secure channel with the TOE component and the subsequent transmission of encrypted data to confirm this functionality. Alternatively, the following steps shall be performed: The evaluator induces audit record transmission, then reviews the packet capture around the time of transmission and verifies that no audit data is transmitted in the clear.

Test 3: For each type of TOE component that, in the evaluated configuration, is capable of transmitting audit information to another TOE component (as specified in FTP_ITT.1 or FTP_ITC.1, respectively), the evaluator shall configure a secure channel and confirm that audit records generated as a result of actions taken by the evaluator are securely transmitted. It is sufficient to observe negotiation and establishment of the secure channel with the TOE component and the subsequent transmission of encrypted data to confirm this functionality. Alternatively, the following steps shall be performed: The evaluator induces audit record transmission, then reviews the packet capture around the time of transmission and verifies that no audit data is transmitted in the clear.

While performing these tests, the evaluator shall verify that the TOE behaviour observed during testing is consistent with the descriptions provided in the TSS and the Guidance Documentation. Depending on the TOE configuration, there might be a large number of different possible configurations. In such cases, it is acceptable to perform subset testing, accompanied by an equivalency argument describing the evaluator’s sampling methodology.
