= CCUF Team Tools Working Group
:showtitle:
:imagesdir: images
:revnumber: 0.6
:revdate: 2019-09-13

include::menu-include.adoc[]

== Introduction
The CCUF established the Team Tools Working Group to work on a set of tools for iTCs. The overall goal is to produce a set of guidance documents on how to use the tools for an iTC and templates for the documents the iTC will need (both to product, such as a cPP and for the processes of managing the iTC itself). The output from this group is intended to be freely available to all iTCs, and will hopefully be maintained over the long term.

The work is being done in GitHub at https://github.com/itc-wgtools/cPP-Tools.

The https://github.com/itc-wgtools/cPP-Tools/wiki[wiki] has a list of meeting notes as well as a lot of other related information that doesn't fit neatly into the templates or the web pages here.

*PLEASE join the Team Tools WG!* Send a message to: ccuf-team-tools-wg+subscribe@googlegroups.com

To see the calendar for calls/meetings, go to: http://localendar.com/public/itctools

== Tools and Guidance
Any set of tools on its own isn't very useful, so in conjunction with the tools in GitHub is a set of documentation provided on this site to help explain how to use the tools and some of the general back end work that needs to be done to support the iTC.

The guidance is broken into several areas:

* link:/admin-guide/index.html[Administrator Guidance]
* link:/user-guide/index.html[User Guidance]
* link:/examples/examples.html[Examples for the cPPs and SD]
* https://github.com/itc-wgtools/cPP-Tools/wiki/Recommended-External-Tools[Recommended External Tools]
* link:/files_list.html[Description of currently available templates]

Documents that are available for public review can be seen at the link:/drafts/drafts.html[Drafts] page. This will include information about submitting comments to the WG.

== Current Status
The WG is working towards the completion of the documentation in time for the https://www.iccc2019.com/[ICCC 2019]. As a volunteer effort, we were able to complete the majority of the immediate link:/files_list.html[documents] an iTC would need. As we move past the ICCC more documents related to the administration of the iTC itself will be produced. 

[ditaa, "Current_Status"]
....
                                  
    +----------+    +----------+   +----------+   +----------+   +----------+
    |          |    |          |   |          |   |          |   | cGRE     |
    | Phase 1  |    |  Public  |   | Phase 2  |   |  Public  |   | Public   |
    | Drafts   |--> |  Review  |-->| Drafts   |-->|  Review  |-->| Release  |
    |          |    |  Phase 1 |   |          |   |  Phase 2 |   |          |
    |          |    | (June 25)|   |          |   |  (Aug30) |   | ICCC2019 |
    +----------+    +----------+   +----------+   +----------+   +----------+

....

== Public Presentation of the Work
At the CCUF meetings in April 2019, the initial public presentation of the Tools WG was presented. This presentation can be found here: https://youtu.be/6Gdb4qNn0tg (note that this is 1:22 long). This focused on the thought process behind the direction and the plans at that point.

== Eating Our Own Dog Food
This WG has been attempting to use what we are providing for the wider community. This has helped (and probably hurt initially as we all learned from the experience, but that was the point), but hopefully the efforts of the WG will benefit the wider community as we go forward.