= Coffee Maker iTC
:showtitle:
:toc:
:imagesdir: images
:icons: font
:revnumber: 0.1
:revdate: 2019-08-22

:iTC-longname: Coffee Maker
:iTC-shortname: CM-iTC
:iTC-email: cm.itc@gmail.com
:iTC-website: https://coffeemaker.github.io/
:iTC-GitHub: https://github.com/coffeemaker/repository/

== Introduction
From the CCDB-established Working Group, the {iTC-longname} ({iTC-shortname} for short) was formed. The {iTC-shortname} consists of members of Certification Bodies, labs, vendors and academia working together to create requirements for biometric security testing.

https://www.commoncriteriaportal.org/communities/<page>[Common Criteria Portal {iTC-shortname} Page]

To join the {iTC-shortname}, please send a message to: {iTC-email}

== Resources related to the {iTC-longname} iTC

[GUIDANCE]
====
These are example links for resources. Probably important to have a library page that links to all iTC governing docs. For example, Public Review process, IT process, ToR, ESR, could all go on a library page, but things that are likely to be hit up often, maybe should be listed directly. 
====

* link:/cPP/cPPv01.html[cPP v0.1]
* link:/SD/SDv01.html[SD v0.1]
* link:/library.html[Documentation Library]
* link:/docs/public-review-process.html[Public Review Process for {iTC-shortname}]
* link:/public-review/status.html[Public Review Status]
* {iTC-GitHub}[{iTC-shortname} GitHub repository]

== Current Status
Put something here that talks about what is going on right now. This isn't as formal as say the draft status, but something that may say something like "working on the initial draft release of the cPP". The idea would just be to say something about what is going on within the iTC.

