= GitHub Training References
:showtitle:
:imagesdir: images
:icons: font
:revnumber: 0.1
:revdate: 2019-08-01

== Introduction
Git can be a little counterintuitive at first, but once familiarized it can be easy to navigate around and understand what's happening. Several resources can be used to better learn how to work with it:

GitHub Guides:: Github provides a comprehensive set of learning tools to get new users acclimated to working with git. URL: https://guides.github.com
Learning Lab:: The learning lab is an interesting learning resource, because it uses a robot to interact with the user in a teacher/student scenario.

*To Install the Learning Lab*

* Go to https://lab.github.com
* Sign into GitHub and scroll to the bottom of the page. The Getting Started guide will walk you through installation of the app, and registering for a course. 

Once complete go to your profile on github, click the learning path added (it'll be a repository), and start learning!

[NOTE]
====
The Learning lab is not a requirement per se. It is however a powerful way to learn how to work with git and GitHub in general so it's at least worth looking into.
====