= PP-Configuration for _Protection Profile 1_ and _Protection Profile 2_
:showtitle:
:toc:
:table-caption: Table
:revnumber: 0.8
:revdate: 2019-01-31

== Acknowledgements

This PP-Configuration was developed by the _your_ international Technical Community (iTC) with representatives from industry, Government agencies, Common Criteria Test Laboratories, and members of academia.

:sectnums:

== Introduction

=== Overview

The purpose of a PP-Configuration is to define a Target of Evaluation (TOE) that combines Protection Profiles (PPs) and PP-Modules for various technology types into a single configuration that can be evaluated as a whole. 

_Define the scope of the combined system that would be covered by the PP/PP-Modules in this configuration._

=== PP-Configuration Reference

This PP-Configuration is identified as follows:

* _List the PPs/PP-Modules to be covered by this document_
* As a shorthand reference, it can be identified as "__some short name__"

=== PP-Configuration Components Statement

This PP-Configuration includes the following components:

* Base-PP: _Reference the Base-PP_
* PP-Module: _Reference the PP-Module (this could also be another PP)_

NOTE: If the configuration covers multiple PPs/PP-Modules they can all be listed here, but this is not required. For example, combinations with the MDFPP to date have not included the WLAN EP (not yet a PP-Module), even though that is required for the MDFPP, because the WLAN requirements do not interact in any way with the combinations being proposed (to date). If this is a specific configuration though that covers explicitly a Base-PP and more than one PP-Module or other PP, then they should all be listed here. 

=== Revision History

[cols=",,",options="header",]
|===
|*Version* |*Date* |*Description*
|0.8 |31 Jan, 2019 |First draft for review
|===

== Conformance Claims

=== CC Conformance

*Conformance Statement*

To be conformant to this PP-Configuration, an ST must demonstrate Exact Conformance, as defined by the CC and CEM addenda for Exact Conformance, Selection-Based SFRs, and Optional SFRs (dated May 2017).

NOTE: This example is from a NIAP-generated PP-Configuration for Exact Conformance. If the PP has other requirements, different conformance statements would be required.

*CC Conformance Claims*

This PP-Configuration, and its components specified in section 1.3, are conformant to Parts 2 (extended) and 3 (conformant) of Common Criteria Version 3.1, Release 5 [CC].

=== SAR Statement
The set of SARs specified for this PP-Configuration are taken from, and identical to, those specified in the Base-PP.

NOTE: Normally the above statement is likely to be sufficient for a PP-Configuration. Where there may be some differences (such as merging different PPs), then a table with how the claims are combined and managed will be necessary.

=== Related Documents

**Common Criteria**footnote:[For details see http://www.commoncriteriaportal.org/]

[cols=",",]
|===
|[CC1] |Common Criteria for Information Technology Security Evaluation, +
Part 1: Introduction and General Model, +
CCMB-2017-04-001, Version 3.1 Revision 5, April 2017.
|[CC2] |Common Criteria for Information Technology Security Evaluation, +
Part 2: Security Functional Components, +
CCMB-2017-04-002, Version 3.1 Revision 5, April 2017.
|[CC3] |Common Criteria for Information Technology Security Evaluation, +
Part 3: Security Assurance Components, +
CCMB-2017-04-003, Version 3.1 Revision 5, April 2017.
|[CEM] |Common Methodology for Information Technology Security Evaluation, +
Evaluation Methodology, +
CCMB-2017-04-004, Version 3.1 Revision 5, April 2017.
|[addenda] |CC and CEM addenda, +
Exact Conformance, Selection-Based SFRs, Optional SFRs, +
Version 0.5, May 2017.
|===

*Protection Profiles*

NOTE: This section is optional but is a good reference to have (and you can use the references here as shorthand in the document).

[cols="1,3"]
|===
|[Base-PP] 
|Some Base-PP with all version/identification info

|[PP-Module] 
|Some PP-Module with all version/identification info
|===


