= Public Review Draft 1 of the _Coffee Maker_ iTC <Document(s) for review>
:showtitle:
:toc:
:toclevels: 3
:table-caption: Table
:revnumber: 0.1
:revdate: 2019-06-13
:xrefstyle: full

:iTC-longname: Coffee Maker
:iTC-shortname: CM-iTC
:iTC-email: cm.itc@gmail.com
:iTC-website: https://coffeemaker.github.io/
:iTC-GitHub: https://github.com/coffeemaker/repository/

== Introduction

[IMPORTANT]
====
This document calls the review period "Public Review Draft 1" and shows covering multiple documents at one time. Other terms can be used for the review (I have seen "Working Draft/Implementation Draft" and others). Any term can be used, but be consistent throughout the document.
====

This is an announcement of a public review period for the <document(s) for review> from the {iTC-shortname}. 

[NOTE]
====
A description of the expectations of the review period should be placed here.
====

This document will provide information about where to find the documents, how to provide feedback and information about the current status of the documents.

Please email {iTC-email} if there are any questions about the Review process.

The latest status of the Review Period, including the latest copies of any documents, can be found at the {iTC-website}[{iTC-longname} page].

[NOTE]
====
The "easiest" site will be to claim a github.io site by creating a repository for it (see the Admin Guide documents) since it is free and only requires the creation of the repository (and adding of HTML docs which can be output from Asciidoctor files). Any site can be used though to publish the documents and status.
====

== Review Status Phase
The documents listed here are in the *Public Review Draft 1* phase.

Publication Date:: <start date>
End of Comment Period:: <end date>

== Documents for Review

The following are the documents included in this Public Review Draft 1 Period:

.Review Documents
[[DocTable]]
[cols="3,1,2",options="header"]
|===
|Title ^|Version ^|Link

|collaborative PP for {iTC-longname} feature
.^|0.8
^.^|{iTC-website}cPP-filename.pdf[Download cPP]

|PP-Configuration for base-cPP and PP-Modules
.^|0.8
^.^|{iTC-website}PPC-filename.pdf[Download PP-Configuration]

|Supporting Document Mandatory Technical Document: Evaluation Activities for collaborative PP-Module for Mobile biometric enrolment and verification - for unlocking the device -
.^|0.3
^.^|{iTC-website}SD-filename.pdf[Download Supporting Document]

|===

The following are the documents to use in support of the Public Review Draft 1 Period.

.Supporting Documents
[[SupDocTable]]
[cols="1,1",options="header"]
|===
|Title ^|Link

.^|Comment Matrix
^|{iTC-website}Comments-Matrix.xlsx[Download Comment Matrix]


|===

== Document Release Process
The {iTC-shortname} follows the document release process below for the publication of documents. Generally the cPP and SD would be released at the same time.

[ditaa]
....
                                  
    +----------+    +----------+   +----------+   +----------+   +----------+
    |          |    |  cYEL    |   | Public   |   |          |   | Public   |
    | Internal |    |  Public  |   | Review   |   |  Public  |   | Review   |
    |  Draft   |--> |  Review  |-->| Draft 1  |-->|  Review  |-->| Draft 2  |-+
    |          |    |  Draft 1 |   | Update   |   |  Draft 2 |   | Update   | |
    |          |    |  (45d)   |   | (60d)    |   |  (45d)   |   | (60d)    | |
    +----------+    +----------+   +----------+   +----------+   +----------+ |
                                                                              |
            +-----------------------------------------------------------------+
            |   +----------+   +----------+   +-----------+
            |   |          |   |          |   |           |
            |   | Proposed |   | Proposed |   | Final     |
            +-->|  Draft   |-->|  Update  |-->| Document  |
                |          |   |          |   | Published |
                | (30d)    |   | (10d)    |   |           |
                +----------+   +----------+   +-----------+
....

.Review Timeline
[[timeline]]
|===
|Phase |Time |Description

|Internal Draft
|
|The normal, pre-release process for creating the documents

|Public Review Draft 1
|45 days
|{iTC-shortname} has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 1 Update
|Up to 60 days
|The {iTC-shortname} will review all received comments and update the documents accordingly

|Public Review Draft 2
|45 days
|{iTC-shortname} has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

PAD Toolbox drafts will be published with this review (final review on toolboxes may proceed independently from rest of documents).

|Public Review Draft 2 Update
|Up to 60 days
|The {iTC-shortname} will review all received comments and update the documents accordingly

|Public Review Draft 3 (Optional, not shown)
|45 days
|{iTC-shortname} has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 3 Update (Optional, not shown)
|Up to 60 days
|The {iTC-shortname} will review all received comments and update the documents accordingly

|Proposed Draft
|30 days
|{iTC-shortname} has voted according to Terms of Reference to propose this as the final document. Public (i.e. from non-iTC participants) comments are accepted during this period

|Proposed Update
|10 days
|{iTC-shortname} reviews any further comments and prepares the document for final publishing (updating all dates, producing official versions for publication)

|Final Document Published
|
|Documents are posted to Common Criteria Portal

|===

The {iTC-shortname} may decide, based on the comments received during the Public Review Draft 2 period, that a Public Review Draft 3 period is needed. Public announcement of a third Review Draft or a Proposed Draft will be made once all comments have been addressed.

=== Review Process
There are two ways to contribute comments and suggestions to the {iTC-shortname}. The first is through GitHub, the second by spreadsheet. It should be noted however that comments that are received via the spreadsheet will be added to the GitHub platform to allow for a comprehensive discussion. Also, feedback for comments is only provided via the answers in the GitHub. 

Each comment should have a suggested resolution be proposed if a change is needed to the document.

==== GitHub Review Process
To use GitHub to submit comments, you must have a GitHub account (and it is assumed you know how to use GitHub). Each comment should be submitted as an individual {iTC-GitHub}/issues[Issue] with the Label "Public Review" assigned. Pull Requests created for any issues will be linked to these Issues for traceability.

==== Comment Matrix Spreadsheet Review Process
In the <<SupDocTable>> table there is a link to the Comment Matrix spreadsheet. There are instructions for using the Matrix on the second worksheet. Please create a separate copy of the spreadsheet for each document.

Email the spreadsheets to {iTC-email}.

== Additional Notes
The documents under review are the current state of output. Two major areas of discussion within the {iTC-shortname} that are still under consideration within are noted below. 

[NOTE]
====
There may not be anything to go here in which case leave it out. This is for specific topics you want reviewers to focus on or provide explicit input on (or to ignore a section you are still working on but want the rest of the document reviewed).
====

Comments on these specific topics can be made separately.

=== Issue 1
A description of the first issue and any specific direction you want to provide to people reviewing the documents.

=== Issue 2
A description of hte second issue and any specific direction you want to provide to people reviewing the documents.
 
