= Asciidoctor Generating Output with itc_gentools
:showtitle:
:toc:
:imagesdir: images
:icons: font
:revnumber: 0.1
:revdate: 2019-08-01

include::submenu-include.adoc[]

== Introduction
At this point there are two types of output that are supported from Asciidoctor: HTML and PDF. The same source file can be used to generate both types of output files, just using different commands from the tools that have been installed.

For simplicity, use the tools installed as part of the setup. The itc_gentools package should cover the majority of output generation for HTML and PDF files automatically.

The itc-gentools script provides a simple method for creating the HTML and PDF files automatically using the Asciidoctor tools that were installed during the setup.

== The itc_gentools Ruby Gem Package
The itc_gentools package can be found https://github.com/itc-wgtools/itc_gentools[here]. The latest version can be seen listed in the README.

=== Installation of itc_gentools
To install the package, you will need to download the GEM file for the latest version. On the home page of the tool, click the link for the latest version. On this page you will see a file called

  itc_gentools-X.Y.Z.gem

where X.Y.Z is the version number. Download this file so you can access it via the Ruby command prompt.

[IMPORTANT]
====
The installation process assumed you have already installed Ruby on the computer as specified in the setup instructions. If you have not, then do that now.
====

To install the Gem, run the command

  gem install itc_gentools-X.Y.Z.gem

(remember to enter the proper version number).

The itc-gentool.rb script provides a simple method for creating the HTML and PDF files automatically using the Asciidoctor tools that were installed during the setup.

=== Generating Output
Once you have placed the Asciidoctor file into the <input> folder, to generate output, run the following command:

  itc-gentool <output type> <source file>

Running the script without any parameters will show a help message.

[IMPORTANT]
====
If you are embedding any images (as opposed to generating them like through ditaa), make sure you copy the images folder along with the Asciidoctor file to the input folder.
====

The following <output type> parameters are accepted (not case sensitive).

.itc-gentool Output Type Parameters
[cols="1,3",options="header"]
|===
|Parameter
|Description

|html
|produces an HTML file from the source file

|pdf
|produces a PDF file from the source file

|both
|produces both HTML and PDF files from the source file

|===

The script checks for the existence of an output file by the same name before publishing the file (Asciidoctor will automatically overwrite the file by default). If the output file already exists, the script will abort. This especially important when using "both" as the output type since it means you will not have files generated from different versions of the same source file.

== Direct Use of Asciidoctor tools
For simplicity and consistency, it is recommended to use the itc_gentool script, but there could be times when more flexibility is necessary. The following sections specify the command line parameters that are being used in the script.

[IMPORTANT]
====
The provided script is based on the expectations for use at the time it was created. If you determine there are other features that are needed or changes you have made, please provide this feedback to the iTC Tools WG so they can be shared with the wider community.
====

The <itc_gentools HOME> is the installed location of the package.

=== HTML Command Line Parameters
If you have a need to run the Asciidoctor HTML generation directly instead of through the provided scripts, the following parameters must be added for consistent output (in addition to the input filename).

Note that it is possible to skip some of these if you do not need the feature offered, but having it enabled and not using it does not cause any problems, so the above scripts always call these for consistency.

The following is the current HTML command line being used in the script.

  asciidoctor -r <itc_gentools HOME>/notice-block.rb -r asciidoctor-diagram -a data-uri -a toc=left -D <output folder> sample.adoc

The parameters are specified in the table below.

.HTML Asciidoctor Parameters
[cols="1,2",options="header"]
|===
|Parameter
|Description

|-r asciidoctor-diagram
|Enables ditaa graphics generation output

|-r <itc_gentools HOME>/notice-block.rb
|Calls the iTC admonition block for custom icons. This

This enables the graphics in the templates for iTC guidance, and should be used to help spot sections that may not have yet been removed.

|-a data-uri
|This will embed the graphics into the output (so the HTML page is more portable)

|-a toc=left
|When generating HTML output this makes the TOC a sidebar on the left (instead of placed inline at the top of the page)

|===

=== PDF Command Line Parameters
If you have a need to run the Asciidoctor PDF generation directly instead of through the provided scripts, the following parameters must be added for consistent output (in addition to the input filename).

Note that it is possible to skip some of these if you do not need the feature offered, but having it enabled and not using it does not cause any problems, so the above scripts always call these for consistency.

The following is the current PDF command line being used in the script.

  asciidoctor-pdf -r <itc_gentools HOME>/notice-block.rb -r asciidoctor-diagram -a pdf-theme=<itc_gentools HOME>/themes/admonition-theme.yml -D <output folder> sample.adoc

.PDF Asciidoctor Parameters
[cols="1,2",options="header"]
|===
|Parameter
|Description

|-r asciidoctor-diagram
|Enables ditaa graphics generation output

|-r <itc_gentools HOME>/notice-block.rb
|Calls the iTC admonition block for custom icons. This

This enables the graphics in the templates for iTC guidance, and should be used to help spot sections that may not have yet been removed.

|-a pdf-theme=<itc_gentools HOME>/themes/admonition-theme.yml
|This goes along with the notice-block and must be used together to properly render the icons.

|===