= iTC Documentation Workflow
:showtitle:
:toc:
:toclevels: 7
:sectnums:
:sectnumlevels: 7
:imagesdir: images
:icons: font
:revnumber: 0.1
:revdate: 2019-11-15

include::submenu-include.adoc[]

:sectnums!:

== Introduction
While this is titled the iTC Documentation Workflow, this is about both the initial creation and the ongoing updates that will happen during the lifecycle of the documents. Generally this has been called "maintenance" in some other places in the guidance documentation, in part due to a focus on what will be done after the first version has been published. 

The workflow described here utilizes GitHub Projects to help manage the prioritization of issues and the associated work on them. The setup for the Project is part of the link:index.html[iTC Administrator Tools Overview].

:sectnums:
== Projects & Releases
Projects in GitHub are generally tied to specific releases, and not for "ongoing" work. The Maintenance project template has been created following this expectation. A repository can have multiple projects, so it is possible to be working towards multiple releases at the same time (usually on different timeframes).

For example from a v1.0, there would be a maintenance project for v1.1. There should also be a maintenance project for a v1.2, or v2.0, that could be used to hold items that need to be worked on later. Once work was completed on v1.1 and it was published, that project would be closed, and the focus would move to the next project.

In short, a project would be tied to a specific release version of the cPP/SD, and used to track progress until completion, at which time it would be closed.

=== Notes for Overall Goals
Within the project it is possible to create Notes. This can be done using the + symbol in the column header. This can be used by the Editor team to specify the list of targets for the next release (such as a bullet list of items to be tackled). This can be added in the To Do column for easy tracking (they can be in one list or per item, though with the per item they can be moved along with the issues as they are worked on, which may be useful). 

=== Parking Lot/Future Undetermined "Projects"
While this document is focused specifically on maintenance targeted to an existing document, there will be times when useful or valid requests do not have a determined need or timeframe for inclusion. 

These can be handled many ways, but one way is to use the Parking Lot label. Another way to handle this is to create a "futures" template (say a v2.0 if you are on v1.1) that could be "far in the future", and add these issues to that project. 

Either way, the issues can be found (going to the future project or filtering on the parking lot label), and provides a way to keep track of issues to handle over time.

== Editors Team
One of the recommended GitHub teams to setup is the Editor team. This is the team that is considered to be in charge of the final documentation. Likely, these are also the primary contributors to the cPP/SD, but that does not need to be the case.

From the standpoint of maintenance and release, the Editor team is responsible for the master branch of the published version of the documents. Once the iTC has agreed that the working draft is ready for publication, it is up to the Editor team to move the draft into the master branch and to produce the final output (i.e. the HTML/PDF copies of the documents).

The Editors team should be a small group (preferably at least 3, but probably not more than 8 depending on the size of the iTC membership). 

== Documentation Workflow
The process of creating the cPP/SD would roughly go something like this:

. iTC determines a document is needed (initial or a new version)
. iTC establishes a project to track the process for the document
. Using the Working branch, members of the iTC submit issues and make updates
. Members of the iTC approve changes to the working branch
. Members of the iTC approve the "final" version in the working branch as ready for publication
. Members if the Editor Team merge the working branch into the master branch and publish the new release

=== Using the Maintenance Project
Once a Maintenance project has been setup, the iTC should be able to use it to manage the open issues that are raised during the editing cycle. 

To track issues (and pull requests) in a project, they must be assigned to the project. When creating/editing an issue or pull request, the specific Project must be set in the metadata on the right hand side (along with Assignees/Reviewers, Labels and Milestones).

The following diagram shows the phases in the Maintenance workflow.

[NOTE]
====
These are provided as a stock workflow that is expected to be able to work well. An iTC can make any adjustments the feel necessary for their own needs. It is requested that any adjustments or issues that are found with this process be sent back to the Team Tools WG to share the information with other iTCs.
====

[#img-Maintenance-Workflow] 
.Component levelling 
[ditaa,"Maintenance-Workflow.png"]
....
 +-------+    +----------+    +----------+    +----------+    +----------+
 |       |    |          |    |          |    |          |    |          |
 | To do |--->| Awaiting |--->| Awaiting |--->|   In     +--->| Complete |
 |       |    | Priority |    |  Review  |    | Progress |    |          |
 |       |    |          |    |          |    |          |    |          |
 +-------+    +----------+    +----------+    +----------+    +----------+

....

The following table provides a high level overview of each phase of the workflow.

.Workflow Description
[[Workflow]]
[cols="1,1,3",options="header"]
|===
|Phase/Label 
|Involved Members 
|Description

.^|To Do/New Issue
.^|Editor Team (after issue is created)
|This is the point where the Editor Team will triage incoming issues that have been created and assigned to this Project. 

.^|Awaiting Priority
.^|All members
|Once an issue has been initially reviewed, it moves to the iTC membership to prioritize the issue. Several labels are provided to help provide values to assign rank. 

The Editor Team manages the list of items and would be responsible for determining when an issue should be assigned for work.

.^|Awaiting Review
.^|Assigned Members (or all until assigned)
|At this point an issue has been agreed to be worked on (in some sort of prioritization), and is now waiting to begin.

.^|In Progress
.^|Assigned members
|This shows that the issue is being worked on (and should also generate a pull request associated with the issue that would appear here).

.^|Complete
.^|
|This is automatic when the issue is closed
|===

The movement through the phases is handled by the Labels assigned to the Issue. An Issue may have labels such as enhancement or bug, but nothing related to its status. Within the project this will place them in the To do phase. To move to the next phase, the Editors would change the Labels, which will move the project to the next phase (or column in the display). 

To readily move the issues through the workflow, removing the current label and placing the next label (for example removing the Awaiting Priority label and adding the Awaiting Review label) will move the issue automatically to the next phase of the project.

==== To Do Phase
.To Do Rules
[cols="1,2",options="header"]
|===
|Label/Rule
|Description

.^|New Issue
|When a new issue is created and added to this project it is added here.

|===

The To Do phase starts when a new issue has been created and added to the project. Issues may be labeled differently depending on how the issue has been created or what the author thinks is the best choice among the available options. 

If a new issue is created using an Issue Template, it will be labeled as an enhancement. This is something that can be adjusted to meet the needs of the iTC.

[IMPORTANT]
====
Issues created from the templates should have Editors assigned (assuming those steps were followed during the setup of the repository) so they will automatically receive notifications when they are created. For issues created without the template, unless the creator specifically assigns someone, there will be no notification, so it will be up to the Editors to check for new issues on a regular basis.
====

The Editor team here should be reviewing the new issue and categorizing it for further review. This is basically a triage point where the Editors should try to determine how to handle the Issue.

Some examples of what could be done here (this should not be considered exhaustive):

* Accept the Issue and assign it to the Awaiting Priority queue
* Close the Issue (such as marking it as Invalid or Not Fix)
* Mark the issue as a duplicate (reference the duplicate issue) and close
* Move the Issue to a different project (for example a later planned update)
* Place the Issue on the agenda for discussion on the next scheduled meeting

==== Awaiting Priority Phase
.Awaiting Priority Rules
[cols="1,2",options="header"]
|===
|Label/Rule
|Description

.^|Awaiting Priority
|Once it has been determined the Issue should likely be handled in the next update, it should be assigned a priority within the work queue.

|===

The Awaiting Priority phase is what would be considered the first open to the iTC phase. At this point the iTC members should review the issue to assign weighting to the issue. The weighting is designed to be fairly general but provide the Editors with a way to see the relative ranking of issues to provide better prioritization.

While this should be discussed in the issue (the reasons for assigning the weightings), the following table shows the labels that are provided and some ideas about why they may be assigned. These are not hard and fast rules, but should provide good guidance to get started.

.Prioritization Weighting Labels
[cols="1,2",options="header"]
|===
|Label
|Examples

.^|Applicability +2
|Request is from a Scheme supporting the iTC

.^|Applicability +1
|There are/were similar requests that have not been considered previously

Request originates from an unrelated organization but is similar/closely related to one already under consideration (could be a parking lot item)

.^|Agreement +2
|Request has a Scheme-proposed or iTC consensus-based solution

.^|Urgency +2
|Request is related to an active evaluation (should be moved to IT unless not critical)

.^|Coupling +2
|Request is unreasonably broad in scope or contains more than one unrelated issue

.^|Effort +2
|Request is lacking a clear problem description and rationale

Request is lacking a clear proposed solution

.^|Risk +2
|The solution to the request is likely to impact multiple inter-related requirements

.^|Risk +1
|The request is asking to set aside reporting requirement

The request is asking to set aside or modify a testing or functional requirement

|===

The members of the iTC (as overseen by the Editor team) can add/remove the proposed labels to the issue to assign the overall priority. In some cases the iTC may determine that some weight labels should be approved by the iTC while others may be able to be assigned directly. The purpose of the comment tracking is to provide this justification prior to the assignment of the final priority to someone to work on.

[IMPORTANT]
====
Each added weighting label should have an associated entry in the issue comments to justify the addition (or removal) of the label.
====

Within the Maintenance Project itself, the Editors can adjust the ordering of the items according to the labels assigned. This can be done by dragging the issues in the Awaiting Priority column into the desired order. While Issues that have been just added will always list at the top, it is possible to easily move them at any time (and the rest of the list will remain in the same order it has been set to).

Once issues have been assigned a priority to work on it, it can be assigned to members to work on. This will help people prioritize the issues they work on, based on the agreed importance of the issue.

Editors should note the final agreed priority (likely determined during a meeting) in the issue at the time it is moved to the next phase and assigned.

==== Awaiting Review Phase
.Awaiting Review Rules
[cols="1,2",options="header"]
|===
|Label/Rule
|Description

.^|Awaiting Review
|Once an issue has been assigned a priority for the project, it will be assigned to members to work on.

|===

The Awaiting Review phase is more like a holding area until someone has time to start working on the issue. Generally an issue will stay in this state until the assigned member(s) are able to start working on it.

Once someone begins work on the issue (either in research or by starting a pull request), the label should be changed to the In Progress state.

==== In Progress Phase
.In Progress Rules
[cols="1,2",options="header"]
|===
|Label/Rule
|Description

|In Progress
|The issue (pull request) is being actively worked on.

|===

The In Progress phase is the active phase of any issue as it symbolizes that at least one person is working towards closing the issue. This is most likely through the creation of a pull request.

When a pull request is created for the issue in question, it should have a direct reference to the original issue as well as being added to the project with the In Progress label. This will help keep track of the pull request and the issue at the same time in the overall project.

[NOTE]
====
When a pull request is created, if the in the comment the text "closes #55" where 55 is the Issue number, then when the pull request is merged, it will automatically close the issue as well.

See https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords[this page] for more information about keywords that can be used to activate this feature.
====

==== Closed Phase
.Closed Rules
[cols="1,2",options="header"]
|===
|Label/Rule
|Description

|Closed
|The issue (pull request) has been closed (generally would mean a pull request has been created and merged).

|===

The Closed column in the project allows overall tracking on the progress of the issues that have been assigned to the project. Items will automatically be added here as issues and pull requests are closed/merged into the working branch.

=== Approvals & Getting to Closed
During the entire workflow, the goal is to capture the discussion around each issue within the issue itself. Comments into the issue provide context and remain with the issue in the repository history.

Yet the actual changes that will be produced from an issue must be approved before they can be merged into the working draft (and eventually into the master). This is handled automatically by the approval process built into GitHub and setup in the repository branches. While this may be adjusted over time, it is generally recommended that between 25-30% of the membership (or at least the active membership) approve any pull request before it can be merged.

When a pull request is ready for review, the author requests review and approval. This can be to specific members or to teams. Once enough reviews have occurred, the pull request can be merged into the working branch (which will close the pull request and issue).

This process means that it isn't necessary to take a formal vote on the proposed changes (i.e. an email ballot, for example), as the results are automatically tracked as part of the approval process.

== Publishing to the Master Branch
Once all the issues for a project have been completed, the next version of the cPP/SD chould be ready to be published. Members of the Editors team are the only ones who can merge the working branch into the master to create the official version. 

Generally it would be recommended that the membership approve the current working branch in some sort of more formal vote (i.e. outside GitHub following the ToR or other defined voting procedure) for release. Once this is done and approved, the Editor team can create the pull request to merge the working branch into the master and create the published documents (i.e. PDF/HTML copies of the documents).

=== Master Branch Approval
To prevent accidental publication, the master branch should require at least 2 members of the Editor team to approve the pull request to merge the working branch into the master branch. The exact numbers can be adjusted according to the needs of the iTC.